### PR TITLE
Add support for tail latency profiling

### PR DESCRIPTION
**Pull request by kayceesrk**
Rename the tool as `olly`. Add subcommands (using `cmdliner`) for tracing and latency profiling (using hdr histogram).

### CODE REVIEW

**Comment by kayceesrk** [comment]
Here is the change in action:

```bash
$ olly --help
OLLY(1)                           Olly Manual                          OLLY(1)



NAME
       olly - trace an OCaml executable

SYNOPSIS
       olly [--trace-file=TRACEFILE] [OPTION]… EXECUTABLE

ARGUMENTS
       EXECUTABLE (required)
           Executable (and its arguments) to trace. If the executable takes
           arguments, wrap quotes around the executable and its arguments. For
           example, olly '<exec> <arg_1> <arg_2> ... <arg_n>'.

OPTIONS
       -t TRACEFILE, --trace-file=TRACEFILE
           Save the trace in TRACEFILE file in Chrome trace format.

COMMON OPTIONS
       --help[=FMT] (default=auto)
           Show this help in format FMT. The value FMT must be one of auto,
           pager, groff or plain. With auto, the format is pager or plain
           whenever the TERM env var is dumb or undefined.

EXIT STATUS
       olly exits with the following status:

       0   on success.

       123 on indiscriminate errors reported on standard error.

       124 on command line parsing errors.

       125 on unexpected internal errors (bugs).



Olly                                                                   OLLY(1)
```

```bash
$ olly -t menhir_trace.events 'menhir -v --table sysver.mly'
<snip>
#[Mean (ms):    0.03,    Stddev (ms):   0.28]
#[Min (ms):     0.00,    max (ms):      47.94]

percentile       latency (ms)
50.0000          0.00
75.0000          0.00
90.0000          0.01
99.0000          0.80
99.9000          2.54
99.9900          4.98
99.9990          8.59
100.0000         47.94
$ ls menhir_trace.events                                                                       
menhir_trace.events
```

**Comment by sadiqj** [comment]
LGTM. Any downsides to just renaming `runtime_tracer` to `olly`? Will match the public name then.

**Comment by kayceesrk** [comment]
> Any downsides to just renaming runtime_tracer to olly? Will match the public name then.

I don't see any downsides. Let me do that quickly.

**Comment by sadiqj** [comment]
Thanks @kayceesrk

**Pull request merged**
